//
// Purpur Tentakel
// 24.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once



namespace utl {
    struct G_Save_IO final {
        static void LoadGame();

        static void SaveGame();
    };

} // namespace utl
