//
// Purpur Tentakel
// 24.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once

#include <string>


namespace utl {
    enum class G_Save_Enum {
        G_SAVE,

        G_SAVE_VERSION,

        G_SAVE_VERSION_TOTAL_SAVE_ENTRY_COUNT,
        G_SAVE_VERSION_LOAD_SAVE_ENTRY_COUNT,
        G_SAVE_VERSION_SAVE_GAME_VERSION,
    };

    [[nodiscard]] std::string SToS(G_Save_Enum const& type);

} // namespace utl
