//
// Purpur Tentakel
// 24.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once

#include <utils/SaveState.hpp>


namespace app {
    struct G_Save_IO final {
        static void LoadGame(utl::SaveState& saveState, std::string const& dir, std::string const& file);

        static void SaveGame(utl::SaveState const& saveState, std::string const& dir, std::string const& file);
    };

} // namespace app
