//
// Purpur Tentakel
// 20.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once

#include <string>


namespace app {
    class G_Version final {
    private:
        std::string m_game_version = "v0.0.0";
        std::string m_save_version = "v0.0.0.0";

    public:
        [[nodiscard]] std::string get_game_version() const {
            return m_game_version;
        }
        [[nodiscard]] std::string get_save_version() const {
            return m_save_version;
        }

        void set_game_version(std::string value) {
            m_game_version = std::move(value);
        }
        void set_save_version(std::string value) {
            m_save_version = std::move(value);
        }
    };

} // namespace app
