//
// Purpur Tentakel
// 06.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once

#include <string>

namespace cst {
    enum class G_ConfigEnum {
        CONFIG,

        G_FIGHT,
        G_VERSION,
        G_FLEET,

        G_FIGHT_TOTAL_CONFIG_ENTRY_COUNT,
        G_FIGHT_LOAD_CONFIG_ENTRY_COUNT,
        G_FIGHT_HIT_CHANCE,
        G_FIGHT_FLEET_FIGHT_RANGE,
        G_FIGHT_IS_FIGHT_PLANET_FLEET,
        G_FIGHT_IS_FIGHT_TARGET_POINT_FLEET,
        G_FIGHT_IS_FIGHT_TARGET_POINT_TARGET_POINT,
        G_FIGHT_IS_FIGHT_PLANET_TARGET_POINT,
        G_VERSION_TOTAL_CONFIG_ENTRY_COUNT,
        G_VERSION_LOAD_CONFIG_ENTRY_COUNT,
        G_VERSION_GAME_VERSION,
        G_VERSION_CONFIG_VERSION,
        G_VERSION_LANGUAGE_VERSION,
        G_FLEET_TOTAL_CONFIG_ENTRY_COUNT,
        G_FLEET_LOAD_CONFIG_ENTRY_COUNT,
        G_FLEET_MIN_FLEET_SPEED,
        G_FLEET_CURRENT_FLEET_SPEED,
        G_FLEET_MAX_FLEET_SPEED,
    };

    [[nodiscard]] std::string CToS(G_ConfigEnum value);

} // namespace cst
