//
// Purpur Tentakel
// 16.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once



namespace cst {
    struct G_Config_IO final {
        static void LoadConfig();

        static void SaveConfig();
    };

} // namespace cst
