//
// Purpur Tentakel
// 06.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once


namespace cst {
    struct G_ConfigIO final {
        static void LoadConfig();

        static void SaveConfig();
    };

} // namespace cst
