//
// Purpur Tentakel
// 16.03.2024
// This is a generated file. Do not edit this file.
//

#pragma once

#include <alias/AliasUtils.hpp>

namespace app {
     struct AppContext;
}

namespace cst {
    class G_Sound final {
    public:
        friend struct G_Config_IO;
        friend struct app::AppContext;

    private:
        static inline utl::usize constexpr s_total_config_entry_count = 4;
        static inline utl::usize constexpr s_load_config_entry_count = 2;
        bool m_is_mute = false;
        float m_master_volume = 50.0f;

    public:
        [[nodiscard]] utl::usize get_total_config_entry_count() const {
            return s_total_config_entry_count;
        }
        [[nodiscard]] utl::usize get_load_config_entry_count() const {
            return s_load_config_entry_count;
        }
        [[nodiscard]] bool get_is_mute() const {
            return m_is_mute;
        }
        [[nodiscard]] float get_master_volume() const {
            return m_master_volume;
        }

        void set_is_mute(bool const value) {
            m_is_mute = value;
        }
        void set_master_volume(float const value) {
            m_master_volume = value;
        }
    };

} // namespace cst
