#
# Purpur Tentakel
# 02.03.2024
#

header: str = """//
// Purpur Tentakel
// 02.03.2024
// This is a generated file. Do not edit this file.
//\n\n"""

pragma: str = "#pragma once\n\n"

left_bracket: str = "{"
right_bracket: str = "}"


def indent(i: int) -> str:
    return ' ' * (i * 4)
